### PR TITLE
Retry ping command and various other issues with blhost

### PR DESCRIPTION
**Pull request by Lauszus**
You probably want to test this on all platforms, as I have not done much testing.

### CODE REVIEW

**Comment by Lauszus** [comment]
Btw you might want to compile blhost using Travis as well. You should be able to compile it using gcc on both Linux and Mac.

You might want to compile it for Windows using AppVeyor while you are at it, so it can build all executables automatically :)

**Comment by Lauszus** [comment]
You can check out how to automatically build blhost at my repository: https://github.com/Lauszus/blhost.

**Comment by mondalaci** [comment]
It's interesting that the success rate varies wildly, seemingly randomly regardless of the blhost version used. In any case, this fix doesn't work consistently on Linux.

How's things at your side? What specific improvements did you experience? It's worth to try to reproduce the issue at least a dozen times.

You're welcome to spend about a hour on this, but if it takes more than that, please feel free to ignore it because it's not a pressing issue. I'm not even sure that the issue is blhost related and we'll replace blhost in the long run anyways - Agent will send every protocol message eventually.

**Comment by Lauszus** [comment]
I actually did not test it with the keyboard. I have used blhost with another project and those are simply the fixes I implemented to make it work. I don't think I will spend any more time on it at the moment :)

**Comment by mondalaci** [comment]
Ok, no problem at all. Closing this PR then.

**Pull request closed without merging**
